image:
  repository: 824385115935.dkr.ecr.eu-central-1.amazonaws.com/lesson-5-ecr
  tag: latest
  pullPolicy: Always
  digest: "{{ now | unixEpoch }}"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  DJANGO_DEBUG: "False"
  DATABASE_URL: "postgres://django:secretpass@postgres-db-postgresql.default.svc.cluster.local:5432/django_db"
  DB_HOST: "postgres-db-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "django_db"
  DB_USER: "django"               
  DB_PASSWORD: "secretpass" 